### PR TITLE
feat: add upload bypass option for logscreen

### PR DESCRIPTION
**Pull request by alla-uday**
Add support for `shouldUploadEvent` option in `logScreen` for iOS and Android

### CODE REVIEW

**Comment by einsteinx2** [comment]
Currently blocked by the holiday release blackout, will revisit in January.

**Comment by BrandonStalnaker** [comment]
@alla-uday This change seems off to me. For example I don't even see a method signature in iOS that has the method parameter `'shouldUploadEvent:' . Any more context?

**Comment by ualla-mparticle** [comment]
> @alla-uday This change seems off to me. For example I don't even see a method signature in iOS that has the method parameter `'shouldUploadEvent:' . Any more context?

Hey @BrandonStalnaker here's the method https://github.com/mParticle/mparticle-apple-sdk/blob/1bfd09862360f626f4041c3d12bd11ed9667d541/mParticle-Apple-SDK/Include/mParticle.h#L728

**Comment by BrandonStalnaker** [comment]
Ahh the confusion looking at the private repo vs the public repo. Once the the iOS SDK is released with the changes Uday linked we can look at merging here.

**Pull request merged**
